monolog:
  handlers:
    main:
      # change this line
      type: rotating_file
      # add this line
      max_files: 2
      path: '%kernel.logs_dir%/%kernel.environment%.log'
      level: info
      channels: ['!event']
    console:
      type: console
      process_psr_3_messages: false
      channels: ['!event', '!doctrine', '!console']